allowBuilds:
  '@sentry/cli': true
  '@stellar/stellar-sdk': true
  '@swc/core': true
  esbuild: true
  jest-preview: true
  sharp: true
  unrs-resolver: true
  workerd: true
peerDependencyRules:
  allowedVersions:
    wrangler: '4'
overrides:
  turbo-stream: ^3.2.0
